  const eventsList = [
    {
      id: 1,
      title: 'International Symposium on Wind Energy',
      location: 'VIT Chennai',
      date: 'March 2025',
      year: '2025',
      type: 'Organizer',
      images: [
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (1).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (10).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (11).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (12).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (13).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (14).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (15).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (16).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (17).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (18).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (19).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (2).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (20).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (21).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (22).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (3).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (4).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (5).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (6).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (7).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (8).jpg',
        '/Events/International Symposium of Advanced Wind Energy/International Symposium of Advanced Wind Energy (9).jpg',
      ],
      description: 'Intensive hands-on sessions covering advanced meshing strategies, turbulence modeling best practices, and comprehensive validation methodologies for industrial CFD applications.',
      tags: ['Meshing', 'Turbulence', 'Validation'],
      rotation: -2,
      color: '#14ffc8'
    },
    {
      id: 2,
      title: 'IISc Do Drones Workshop',
      location: 'Bangalore, India',
      date: 'March 2025',
      year: '2025',
      type: 'Hands-on Workshop',
      images: [
        '/Events/IISc Do Drone/IISc Do Drone (1).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (2).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (3).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (4).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (5).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (6).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (7).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (8).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (9).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (10).jpg',
        '/Events/IISc Do Drone/IISc Do Drone (11).jpg',
      ],
      description: 'Participated in a hands-on Drone Workshop organized by the Do Drones club at IISc Bangalore. The session began with understanding the theoretical aspects of multirotor flight and control systems. We then spent a full day assembling, calibrating, performing pre-flight checks, and finally flying the S450 drone ourselves. The workshop concluded with an inspiring surprise visit from Dr. S. Somnath, former Chairman of ISRO, who shared valuable insights on India\'s advancements in aerospace and drone technologies.',
      tags: ['Workshop', 'Drones', 'Aerospace'],
      rotation: 3,
      color: '#00d4aa'
    },
    {
      id: 3,
      title: 'National Conference of Wind Engineering (NCWE)',
      location: 'VIT Chennai',
      date: 'March 2024',
      year: '2024',
      type: 'Organizer',
      images: [
        '/Events/NCWE/NCWE (1).jpg',
        '/Events/NCWE/NCWE (2).jpg',
        '/Events/NCWE/NCWE (3).jpg',
        '/Events/NCWE/NCWE (4).jpg',
        '/Events/NCWE/NCWE (5).jpg',
        '/Events/NCWE/NCWE (6).jpg',
        '/Events/NCWE/NCWE (7).jpg',
      ],
      description: 'Served as a member of the organizing committee for the National Conference of Wind Engineering (NCWE) held in March 2024. The event brought together leading experts and researchers in the field, with participation from international delegates and professors from the UK, Italy, Japan, and Germany. Numerous technical papers were presented, accompanied by insightful talks and discussions on the latest advances in wind engineering.',
      tags: ['Organizing', 'Wind Engineering', 'Conference'],
      rotation: 1,
      color: '#005fa3'
    },
    {
      id: 4,
      title: "Drone Workshop and Flight Training",
      location: "VIT Chennai",
      date: "February 2024",
      year: "2024",
      type: "Hands-on Workshop",
      images: [
        "/Events/Drone VITC/Drone VITC (1).JPG",
        "/Events/Drone VITC/Drone VITC (2).JPG",
        "/Events/Drone VITC/Drone VITC (3).JPG",
        "/Events/Drone VITC/Drone VITC (4).JPG",
        "/Events/Drone VITC/Drone VITC (5).jpg",
        "/Events/Drone VITC/Drone VITC (6).jpg",
        "/Events/Drone VITC/Drone VITC (7).jpg",
      ],
      description: "Participated in a hands-on drone workshop at VIT Chennai focusing on UAV fundamentals and flight dynamics. Disassembled and studied a variety of drones, from simple toy models to an S500 kit, and gained practical experience flying the DJI Mavic Pro 3.",
      tags: ["Drones", "Aerospace", "Flight Dynamics", "UAV"],
      rotation: -1,
      color: "#00b890"
    },
  ]

export default eventsList;